services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: '172.28.1.3'
    extra_hosts:
      - 'db:172.28.1.5'
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: typing-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: '172.28.1.5'
volumes:
  db-data:
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24