version: '2.8'
services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: typing-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - db-data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8079:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=devdb
volumes:
  db-data:
