services:
  app:
    image: ghcr.io/su-its/typing-app:dev
    ports:
      - "3000:3000"
    # TODO: NEXT_PUBLIC_ を使わなくなるならこのコメントアウトを外して
    # イメージビルド時ではなくコンテナ起動時に環境変数をセットするように
    #  environment:
    #    API_URL: http://api:8080
  api:
    image: ghcr.io/su-its/typing-server:dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_ADDR: ${DB_ADDR:-db:3306}
    healthcheck:
      test: ["CMD", "curl", "-sS", "localhost:8080/health"]
      interval: 10s
      retries: 10
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: typing-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10

volumes:
  db-data:
