name: Generate OpenAPI TypeScript Client and Document

on:
  push:
    paths:
      - typing-server/openapi.yaml

jobs:
  generate-client:
    name: Generate TS Client
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-nodemodules
        with:
          root: ${{ github.workspace }}/typing-app
      - name: Retrieve the Schema version
        uses: mikefarah/yq@master
        id: get_schema_version
        with:
          cmd: 'yq ".info.version" ./typing-server/openapi.yaml'
      - name: Generate
        shell: bash
        working-directory: typing-app
        # ${SCHEMA_VERSION%%.*} removes the longest substring starting with a period from $SCHEMA_VERSION
        run: |
          SCHEMA_VERSION=${{ steps.get_schema_version.outputs.result }}
          SCHEMA_MAJOR_VERSION=${SCHEMA_VERSION%%.*}
          npx openapi-typescript ../typing-server/openapi.yaml --output ./src/libs/api/v${SCHEMA_MAJOR_VERSION}.ts
      - name: Validate
        working-directory: typing-app
        run: npx tsc --noEmit
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: generate TS code from api schema
        # Do not run on local (see. https://nektosact.com/usage/index.html)
        if: ${{ !env.ACT }}
# TODO
# generate-doc:
