name: CI (typing-app)

on:
  push:
    branches:
      - "ci/**"
      - develop
      - main
    paths:
      - .github/workflows/nodejsci.yml
      - "typing-app/**"
  pull_request:
    branches:
      - "ci/**"
      - develop
      - main
    paths:
      - .github/workflows/nodejsci.yml
      - "typing-app/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./typing-app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-nodemodules
        with:
          root: ${{ github.workspace }}/typing-app
      - name: Try to build
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/typing-app/node_modules
            ${{ github.workspace }}/typing-app/.next/cache
          key: ${{ runner.os }}-bun-cache-${{ hashFiles('typing-app/bun.lockb') }}
          fail-on-cache-miss: true
      - name: Run lint
        run: npm run lint
