name: CI (typing-app)

on:
  push:
    branches:
      - "ci/**"
      - develop
      - main
    paths:
      - .github/workflows/nodejsci.yml
      - "typing-app/**"
  pull_request:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/nodejsci.yml
      - "typing-app/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./typing-app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-nodemodules
        with:
          root: ${{ github.workspace }}/typing-app
      - name: Try to build
        run: npm run build
